DROP TABLE ATTRACTIONTBL;
DROP TABLE FOODTBL;
DROP TABLE MEMBERTBL;
DROP TABLE REVIEWTBL;
DROP TABLE SHOPTBL;
DROP TABLE JINJITBL;
DROP SEQUENCE ROW_SEQ;

CREATE TABLE FOODTBL 
(
  NAME NVARCHAR2(15) NOT NULL 
, PLACE NVARCHAR2(15) NOT NULL 
, PRICE NUMBER(6) NOT NULL 
, CONSTRAINT FOODTBL_PK PRIMARY KEY 
  (
    NAME 
  )
  ENABLE 
);
CREATE TABLE ATTRACTIONTBL 
(
  PLACE NVARCHAR2(20) NOT NULL 
, WAY NVARCHAR2(20) NOT NULL 
, PRICE NUMBER(7) NOT NULL 
, ETC NVARCHAR2(25) 
);
CREATE TABLE JINJITBL 
(
  PLACE NVARCHAR2(20) NOT NULL 
, WAY NVARCHAR2(20) NOT NULL 
, PRICE NUMBER(7) NOT NULL 
, QUANTITY NUMBER(3) NOT NULL 
);

CREATE TABLE SHOPTBL 
(
  ID NVARCHAR2(20) NOT NULL
, PLACE NVARCHAR2(20) NOT NULL 
, NAME NVARCHAR2(20) NOT NULL
, PRICE NUMBER(10) NOT NULL 
, AMOUNT NUMBER(3) NOT NULL
, NUM NUMBER(3) NOT NULL
, CONSTRAINT SHOPTBL_PK PRIMARY KEY 
  (
    NUM 
  )
  ENABLE 
);
CREATE SEQUENCE ROW_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE TRIGGER SHOPTBL_TRG 
BEFORE INSERT ON SHOPTBL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NUM IS NULL THEN
      SELECT ROW_SEQ.NEXTVAL INTO :NEW.NUM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE TABLE MEMBERTBL 
(
  ID VARCHAR2(20) NOT NULL 
, PASSWORD VARCHAR2(20) NOT NULL 
, NAME NVARCHAR2(15) NOT NULL 
, COUNTRY NVARCHAR2(20) 
, CONSTRAINT MEMBERTBL_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);
CREATE TABLE REVIEWTBL 
(
  ID NVARCHAR2(20) NOT NULL 
, CONTENT NVARCHAR2(50) NOT NULL 
, PLACE NVARCHAR2(20) NOT NULL 
, STAR NUMBER(2) 
);

--ATTRACTIONTBL
INSERT INTO ATTRACTIONTBL (PLACE, WAY, PRICE, ETC) VALUES (N'타이베이101', N'일반티켓', '24000', N'성인입장료');
INSERT INTO ATTRACTIONTBL (PLACE, WAY, PRICE, ETC) VALUES (N'타이베이101', N'우대티켓', '21600', N'학생입장료');
INSERT INTO ATTRACTIONTBL (PLACE, WAY, PRICE, ETC) VALUES (N'타이베이101', N'익스프레스티켓', '48000', N'쾌속입장료');
INSERT INTO ATTRACTIONTBL (PLACE, WAY, PRICE, ETC) VALUES (N'타이베이101', N'스카이라인460티켓', '108000', N'전망대입장료');

--JINJITBL
INSERT INTO JINJITBL (PLACE, WAY, PRICE, QUANTITY) VALUES (N'예스진지', N'버스', '35000', '50');
INSERT INTO JINJITBL (PLACE, WAY, PRICE, QUANTITY) VALUES (N'예스진지', N'택시', '119600', '50');

--FOODTBL
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'누가크래커', N'미미', '6300');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'대만호떡', N'스린야시장', '3000');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'꼬치구이', N'스린야시장', '1500');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'우유튀김', N'스린야시장', '1800');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'화덕만두', N'스린야시장', '1800');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'치파이', N'스린야시장', '2500');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'왕자치즈감자', N'스린야시장', '3200');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'코코버블티', N'코코', '1500');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'망고빙수', N'스무시하우스', '8000');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'연어초밥', N'삼미식당', '7000');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'우육면', N'융캉제', '5000');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'굴전', N'닝샤야시장', '2400');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'딤섬', N'닝샤야시장', '600');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'닭날개볶음밥', N'스펀', '2400');
INSERT INTO FOODTBL (NAME, PLACE, PRICE) VALUES (N'땅콩아이스크림', N'스펀', '1600');

--MEMBERTBL
INSERT INTO MEMBERTBL (ID, PASSWORD, NAME, COUNTRY) VALUES ('sunju7420', '1234', N'김선주', N'대한민국');
INSERT INTO MEMBERTBL (ID, PASSWORD, NAME, COUNTRY) VALUES ('hihi', '9876', N'이하이', N'미국');
